### ISSUE TITLE
Show Portfolio tags in the portfolio pages

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#100]
Right now, portfolio items use tags only, and they aren't displayed anywhere. We should change that!

I'm thinking we may actually want two taxonomies here: one for a broader category (so like "user research", or "open source work", or "client project", or "experimental app" or whatever, obviously we'd want to discuss these!) and then a second one for our role.

Category: one per item, displayed on top of the piece title:
<img width="770" alt="Screenshot 2019-11-22 at 14 17 59" src="https://user-images.githubusercontent.com/376315/69433136-f64d2c00-0d32-11ea-9797-f0d91e2253c0.png">

Role: many per item, displayed under "our contributions" section:
<img width="522" alt="Screenshot 2019-11-22 at 14 18 05" src="https://user-images.githubusercontent.com/376315/69433193-1381fa80-0d33-11ea-96f4-3535c93cc7c8.png">

This way, users could filter and view our portfolio by a number of different axes, either the type of work (category) or our role in the project. We could reveal these as needed on the portfolio index page (#22), either as tabs (for category) or as additional filters (for role). These could be especially useful if you want to send someone a page of all the dev work we've done, or all the WordPress projects or whatever, and it'd be useful to have filtering as our portfolio grows. We probably wouldn't want to show all projects on the main index, but we might want to show more if someone's interested in a particular type of work.

I may or may not need help implementing this (I had troubles with tags when I tried to make them work for #96 and gave up) but let's start by figuring out how we want to present & categorise our work.

**Comment by tofumatt** [comment]
I think tags are sufficient, but displaying them is 👍🏻

**Comment by tofumatt** [comment]
Actually we don't have enough items to warrant tags. Let's close for now but revisit if needed.
