### ISSUE TITLE
Blog: make archive pages more visual

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#147]
We have all these og-images for the blog posts now, but the archive pages are still a little bit flat. Let's try incorporating imagery to make them a bit more dynamic.

**Comment by sarahmonster** [comment]
Two options here!


Two-column, which matches the new apps page nicely, but feels a wee bit busy:
![image](https://user-images.githubusercontent.com/376315/96640141-a5ff9500-131a-11eb-9179-e0408d7d829a.png)


....or single-column, which feels a bit more spaced out (and forgives us more for those months where we don't write something!):
![image](https://user-images.githubusercontent.com/376315/96640327-e828d680-131a-11eb-8faa-a2e8209af522.png)

@tofumatt thoughts?

**Comment by tofumatt** [comment]
I much prefer the two-column! 👍🏻
