### ISSUE TITLE
Copyedit & design: Portfolio index page

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#22]
This one's going to be a bit tricky because _portfolios are hard_. 

Let's start by determining what work we want to feature, and then determining the best way of showcasing it. I can think of three different styles:

1. Case study. The sort of in-depth, detailed, process-showing thing I do in my portfolio.
2. Grid of images. Super simple, super lazy.
3. Simple text description (ie, what we have now).

Some combination may work—so case studies for _some_ projects, and a simpler presentation for others. 

We should also include "Octopus Think Labs", which might include all our non-client work... although that could also wind up in the main portfolio section if it makes sense to do so.

**Comment by sarahmonster** [comment]
Two very-very rough ideas here—I'd say probably sensible to choose an overall direction and move into code, rather than spending too much time doing mockups in Sketch.

## Full-width

![Full-width](https://user-images.githubusercontent.com/376315/69480521-ef401f80-0dff-11ea-8ec9-1b23b866c21b.png)

This approach uses a full-width panel for each portfolio item. A bit harder to quickly scan, but shows detail about each project before  you read more. Would work better if we alternate dark/light panels, which we can do.

We can also intersperse testimonials and stats and whatever quite easily by just giving everything a panel.

## Grid

![Grid](https://user-images.githubusercontent.com/376315/69480522-efd8b600-0dff-11ea-9055-34be9f29e73a.png)

This approach shows more items on one screen and may be better for when/if we have a lot of items, or if we want to do dynamic filtering at some point. (See #100!) We can "feature" certain items by making them larger (ie, crossing 2x2 squares  of the  grid, or even just 1x2 or 2x1 or 1x3 or whatnot). Interspersing testimonials may work better if we move them into the grid structure, or if we  have lots of items in the list. We could show additional text (ie, the Rivet text)  on  hover/mouseover as shown, but this  does kind of hide  it  these details on mobile.

@tofumatt Thoughts?

**Comment by tofumatt** [comment]
We discussed this in-person just now, but the consensus was that while I really _like_ the first one, it could be more-suited to "features"—eg. featuring apps and projects on the homepage or elsewhere. The grid option is more flexible, easier to work with, and I think what we should start with for now. I dig them both!

Let's do grid 👍
