### ISSUE TITLE
Should the hamburger menu have a text label?

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#51]
While I loathed the hamburger for an extremely long time, I feel like it's now so ubiquitous as to need no explanation—people look for it when looking for a menu. (Same with search.)

We also have good alternative text to make the meaning clear to non-visual users, so I'm not worried about that.

That said, there is _some_ evidence that having text + icon can be easier for users to grok:
https://conversionxl.com/blog/testing-hamburger-icon-revenue/

(Note that this is based on conversions, not so much usability testing, but still.)

Here's what that might look like here:

<img src="https://user-images.githubusercontent.com/376315/65335440-594c0680-dbbc-11e9-8f57-07e4b27a4e46.png" width=320 />

<img src="https://user-images.githubusercontent.com/376315/65335441-59e49d00-dbbc-11e9-888b-885188c3d045.png" width=320 />

@tofumatt Thoughts?

**Comment by sarahmonster** [comment]
Having thought about it a bit and looping back to it, I think my answer is "yes". It seems like it MIGHT help usability/accessibility, and it certainly doesn't seem to hurt usability or aesthetics, so it's probably worth implementing. 

@tofumatt thoughts?

**Comment by tofumatt** [comment]
I'm definitely for it, and I personally like the small "Menu" and "Close" texts you implemented there. I say let's do it.

To be clear: these aren't ALWAYS required, especially in more of an app context—on an Android device, for instance, there might be enough consistency/familiarity in the rest of the UI that the _visual_ labels aren't needed. But on the web and with the menu where it is: I don't think it hurts. And I like the message it sends: we care about accessibility and straightforward UI 😄
