### ISSUE TITLE
Implement get-a-quote form

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#65]
Since this is the primary goal for the site, I'd say this is high priority to get a v1 iteration working. 

Here's how I'd suggest that we approach this:

v1: As simple as possible. One page, required fields only. (Name, email, details.) No fancy confirmations (really) required, sends to email. We may find this is really all we need. I'll start a PR for this but I may not be able to get it all working on my own.

<img width="833" alt="Screenshot 2019-09-22 at 18 45 40" src="https://user-images.githubusercontent.com/376315/65392128-31e66c80-dd69-11e9-86fd-f25a8cea7f02.png">

v2: The more complex variant that is currently commented out. Two "pages" (steps), checkboxes, etc, confirmation message, bells and whistles. We can do this waaaaaaay later, since the v1 is really what we need most. 

![Screenshot_2019-09-22 Let's talk(1)](https://user-images.githubusercontent.com/376315/65392133-39a61100-dd69-11e9-9fd2-8cf9cdf8811e.png)

**Comment by tofumatt** [comment]
Note: use https://mailthis.to/ for now; if it turns out we get so many emails that it's easier/cheaper to run an API ourselves I'll do that, probably just some kind of serverless thing. I'll probably _eventually_ do that anyway, but for now mailthis.to will work!
